# dmse_add_plugin(<Target> PRODUCT_NAME <name> PLUGIN_CODE <Xxxx> VERSION <x.y.z>
#                 [BUNDLE_ID <com.dehlimusikk.xxx>])
#
# Declares a complete Dehli Musikk plugin product (VST3 / AU / Standalone) as a thin
# wrapper over the shared engine. A plugin repo's whole CMakeLists is ~5 lines: this
# function supplies everything that was previously 65 lines of per-plugin boilerplate —
#
#   * juce_add_plugin with the house constants (DehliMusikk, Dhmk, synth, MIDI-in,
#     VST3 Instrument/Sampler, AU MusicDevice, copy-after-build)
#   * the shared entry point (plugin/PluginEntry.cpp — createPluginFilter)
#   * the converter-output asset glob → juce_add_binary_data (+ DMSE_HAS_ASSETS)
#   * POST_BUILD install of the memory-mapped sample pack into the shared support
#     folder the engine reads at runtime (keyed by product name):
#         macOS:   ~/Library/Application Support/DehliMusikk/<product>/
#         Windows: %APPDATA%/DehliMusikk/<product>/
#         Linux:   ~/.local/share/DehliMusikk/<product>/
#   * the custom Standalone app (plugin/DehliStandaloneApp.cpp) so its .settings file
#     nests under the DehliMusikk folder too
#   * packaging identity metadata → ${CMAKE_BINARY_DIR}/dmse_plugins/<Target>.json
#     (product / bundle id / version / plugin dir / a DETERMINISTIC per-product Windows
#     installer GUID derived from the bundle id) — consumed by packaging/macos/
#     package_all.sh and the Windows installer script.
#   * app icon by convention: if the plugin repo has packaging/icon.png (square,
#     1024×1024 recommended), JUCE bakes it into the bundles at build time — macOS
#     .icns (Standalone .app + plugin bundles), Windows .ico (Standalone .exe).
#     Linux desktop icons come from the tarball installer instead (packaging/linux
#     ships the same PNG and points the .desktop entry at it).
#
# BUNDLE_ID defaults to com.dehlimusikk.<lowercased target>, which matches every
# existing product; pass it explicitly only to deviate.

get_filename_component(DMSE_ENGINE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(DMSE_ENGINE_DIR "${DMSE_ENGINE_DIR}" CACHE INTERNAL "dehli-musikk-sampler-engine root")

function(dmse_add_plugin target)
    cmake_parse_arguments(ARG "" "PRODUCT_NAME;PLUGIN_CODE;VERSION;BUNDLE_ID" "" ${ARGN})

    foreach(required PRODUCT_NAME PLUGIN_CODE VERSION)
        if(NOT ARG_${required})
            message(FATAL_ERROR "dmse_add_plugin(${target}): ${required} is required")
        endif()
    endforeach()
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "dmse_add_plugin(${target}): unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARG_BUNDLE_ID)
        string(TOLOWER "${target}" _slug)
        set(ARG_BUNDLE_ID "com.dehlimusikk.${_slug}")
    endif()

    # App icon by convention (see header). Deliberately NOT under assets/ — the
    # converter cleans and regenerates that folder, which would delete hand-made art.
    set(_dmse_icon_args)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/packaging/icon.png")
        set(_dmse_icon_args ICON_BIG "${CMAKE_CURRENT_SOURCE_DIR}/packaging/icon.png")
        message(STATUS "${target}: app icon from packaging/icon.png")
    endif()

    juce_add_plugin(${target}
        ${_dmse_icon_args}
        COMPANY_NAME            "DehliMusikk"
        BUNDLE_ID               ${ARG_BUNDLE_ID}
        VERSION                 ${ARG_VERSION}
        PLUGIN_MANUFACTURER_CODE Dhmk
        PLUGIN_CODE              ${ARG_PLUGIN_CODE}
        FORMATS                 VST3 AU Standalone
        PRODUCT_NAME            "${ARG_PRODUCT_NAME}"
        IS_SYNTH                TRUE
        NEEDS_MIDI_INPUT        TRUE
        NEEDS_MIDI_OUTPUT       FALSE
        IS_MIDI_EFFECT          FALSE
        EDITOR_WANTS_KEYBOARD_FOCUS FALSE
        COPY_PLUGIN_AFTER_BUILD TRUE
        VST3_CATEGORIES         "Instrument" "Sampler"
        AU_MAIN_TYPE            "kAudioUnitType_MusicDevice"
    )

    target_sources(${target} PRIVATE "${DMSE_ENGINE_DIR}/plugin/PluginEntry.cpp")

    target_compile_definitions(${target} PUBLIC
        JUCE_WEB_BROWSER=0
        JUCE_USE_CURL=0
        JUCE_VST3_CAN_REPLACE_VST2=0
    )

    target_link_libraries(${target} PRIVATE
        dehli_musikk_sampler_engine
        juce::juce_audio_utils
        juce::juce_recommended_config_flags
        juce::juce_recommended_warning_flags
    )

    # Embedded asset bundle (generated by ds-plugin-converter into the plugin's assets/).
    # Samples normally ship as a memory-mapped disk pack (installed below); only the
    # manifest, images and IRs are embedded. samples/*.flac matches nothing for packed
    # plugins but keeps embedded-sample (pre-pack) conversions working unchanged.
    file(GLOB _dmse_assets CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/manifest/index.json"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/manifest/modes/*.json"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/manifest/partials/*.json"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/samples/*.flac"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/ir/*.flac"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/images/*.png"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/images/*.jpg"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/images/*.jpeg")

    if(_dmse_assets)
        juce_add_binary_data(${target}Assets SOURCES ${_dmse_assets})
        target_link_libraries(${target} PRIVATE ${target}Assets)
        target_compile_definitions(${target} PRIVATE DMSE_HAS_ASSETS=1)
        list(LENGTH _dmse_assets _dmse_asset_count)
        message(STATUS "${target}: embedding ${_dmse_asset_count} asset file(s) from assets/")
    else()
        message(WARNING "${target}: no assets in assets/ — plugin will be silent. "
                        "Generate them with the dmse_convert target first.")
    endif()

    # Install the disk sample pack next to where the engine looks for it (one copy
    # serves all formats). No-op with a friendly note for embedded-sample plugins.
    if(APPLE)
        set(_dmse_pack_dest "$ENV{HOME}/Library/Application Support/DehliMusikk/${ARG_PRODUCT_NAME}")
    elseif(WIN32)
        set(_dmse_pack_dest "$ENV{APPDATA}/DehliMusikk/${ARG_PRODUCT_NAME}")
    else()
        set(_dmse_pack_dest "$ENV{HOME}/.local/share/DehliMusikk/${ARG_PRODUCT_NAME}")
    endif()
    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND ${CMAKE_COMMAND}
                "-DSRCDIR=${CMAKE_CURRENT_SOURCE_DIR}/assets/samples"
                "-DDSTDIR=${_dmse_pack_dest}"
                -P "${DMSE_ENGINE_DIR}/cmake/pack_install.cmake"
        VERBATIM)

    # Standalone settings → DehliMusikk folder (see plugin/DehliStandaloneApp.cpp).
    if(TARGET ${target}_Standalone)
        target_sources(${target}_Standalone PRIVATE "${DMSE_ENGINE_DIR}/plugin/DehliStandaloneApp.cpp")
        target_compile_definitions(${target}_Standalone PRIVATE JUCE_USE_CUSTOM_PLUGIN_STANDALONE_APP=1)
    endif()

    # Packaging identity metadata. The Windows installer GUID is a deterministic
    # UUIDv5 of the bundle id — stable across releases (upgrades replace cleanly)
    # and unique per product (installers never replace EACH OTHER), with nothing
    # to hand-maintain.
    string(UUID _dmse_guid
           NAMESPACE 6ba7b810-9dad-11d1-80b4-00c04fd430c8   # RFC 4122 DNS namespace
           NAME "${ARG_BUNDLE_ID}" TYPE SHA1 UPPER)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/assets/samples/samples.pak")
        set(_dmse_pack true)
    else()
        set(_dmse_pack false)
    endif()
    get_filename_component(_dmse_dir "${CMAKE_CURRENT_SOURCE_DIR}" NAME)
    # Clear the metadata dir once per configure: a removed plugin would otherwise
    # leave a stale <Target>.json that the packaging scripts still iterate.
    get_property(_dmse_meta_cleared GLOBAL PROPERTY DMSE_PLUGIN_META_CLEARED)
    if(NOT _dmse_meta_cleared)
        file(REMOVE_RECURSE "${CMAKE_BINARY_DIR}/dmse_plugins")
        set_property(GLOBAL PROPERTY DMSE_PLUGIN_META_CLEARED TRUE)
    endif()
    file(WRITE "${CMAKE_BINARY_DIR}/dmse_plugins/${target}.json"
"{
  \"target\": \"${target}\",
  \"dir\": \"${_dmse_dir}\",
  \"product\": \"${ARG_PRODUCT_NAME}\",
  \"pluginCode\": \"${ARG_PLUGIN_CODE}\",
  \"bundleId\": \"${ARG_BUNDLE_ID}\",
  \"version\": \"${ARG_VERSION}\",
  \"windowsAppGuid\": \"${_dmse_guid}\",
  \"packSamples\": ${_dmse_pack}
}
")
endfunction()
